enum Groups {
	GROUP_TWITCH,
	GROUP_GENERAL,
	GROUP_HISTORY,
	N_GROUPS
};

enum OptionsTwitch {
	OPT_TWITCH_TMI,
	OPT_TWITCH_CHANNEL,
	OPT_TWITCH_NICK,
	OPT_TWITCH_ALERT,
	OPT_TWITCH_PLUGINS,
	N_TWITCH_OPTS
};

enum OptionsGeneral {
	OPT_GENERAL_PLUGINS,
	OPT_GENERAL_LUA_SCRIPTS,
	N_GENERAL_OPTS
};

enum OptionsHistory {
	OPT_HISTORY_ENABLED,
	OPT_HISTORY_FILE_DB,
	N_HISTORY_OPTS
};

struct zl_config *config_init ();
